baseURL = 'https://wizardly-lichterman-87f65d.netlify.app'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "aether"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


[languages]
  [languages.en]
    title = "My New Hugo i18n Site"
    languageName = "English"
    weight = 1
    defaultContentLanguageInSubdir = true
  [languages.gr]
    title = "Η Νεα μου Ιστιοσελιδα"
    languageName = "Greek"
    weight = 2