baseURL = 'https://wizardly-lichterman-87f65d.netlify.app'
languageCode = 'en-us'
title = 'Vote.gov'
theme = "aether"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


[languages]
  [languages.en]
    contentDir = "content/language/en"
    languageName = "English"
    weight = 1
    defaultContentLanguageInSubdir = true
    title = 'Welcome to Vote.gov'
  [languages.gr]
    contentDir = "content/language/gr"
    languageName = "Greek"
    weight = 2
    title = 'Willkommen bei Vote.gov'
  [languages.es]
    contentDir = "content/language/es"
    languageName = "Spanish"
    weight = 3
    title = 'Bienvenida a Vote.gov'
